Fix & improve CSS styling
xournalpp/xournalpp pull request #2726
Opened 2021-01-30 04:01 UTC by personalizedrefrigerator

When in dark mode, the page preview background would still be light.
The preview's background is now styled with CSS. Selectors including
GtkButton and GtkWindow seemed to do nothing. These have been replaced
with button, window, etc. selectors.

![image](https://user-images.githubusercontent.com/46334387/106346544-ca99d000-626c-11eb-9b15-c01fb68d0526.png)

2021-01-30 06:05 UTC, personalizedrefrigerator commented
I'm changing selected action's border from 
![image](https://user-images.githubusercontent.com/46334387/106348806-e5c10b80-627d-11eb-93a6-86da2c3f6a3b.png)
to
![image](https://user-images.githubusercontent.com/46334387/106348778-a8f51480-627d-11eb-9897-5eba1ac32ba8.png), but just in dark mode.

2021-01-30 07:42 UTC, personalizedrefrigerator commented
I've changed how the floating toolbar looks again!
![image](https://user-images.githubusercontent.com/46334387/106350585-25422480-628b-11eb-98bc-3d79dfe57feb.png)
![image](https://user-images.githubusercontent.com/46334387/106350667-a26d9980-628b-11eb-9628-9b880152bcfc.png)

2021-01-30 21:44 UTC, personalizedrefrigerator commented
The most recent commit fixes an issue where the region between PDF pages was filled with white, regardless of the sidebar's background color.
![image](https://user-images.githubusercontent.com/46334387/106368764-0da58300-6301-11eb-9e6f-0ca5449b8a06.png)

This is done by `cairo_clip`ping the drawing region to the preview rectangle, before rendering pages with PDF backgrounds.

Note: `git-clang-format` works locally (`git-clang-format-9`, `git-clang-format-10`, and `git-clang-format-11` all state that `clang-format did not modify any files`.

2021-01-30 21:47 UTC, Technius commented
Looks like CI is broken.

2021-02-22 22:28 UTC, personalizedrefrigerator commented
@Technius Please review!

2021-02-23 06:16 UTC, Technius requested changes
* The sidebar changes work well.
* The floating toolbox charges are a significant improvement over the current look, but the shadows and transparency hurt readability. Top image is white background with light theme, bottom image is dark background with light theme.
![image](https://user-images.githubusercontent.com/1066652/108806719-50045d80-7557-11eb-93b7-9cdeef9bc6f1.png)
![image](https://user-images.githubusercontent.com/1066652/108806809-9a85da00-7557-11eb-91ab-de5d76041efc.png)
* Also, the inset shadow looks really weird. I think a "popover" effect would be better. For example, make the toolbox solid white (or black, depending on the theme color) with the shadow (white shadow if dark?) outside of the toolbox.
* The icon highlights are going to depend a lot on the theme. For example, they look terrible with my theme, as you can see.
* I get this error in the console on startup:
  ```
  (xournalpp:94836): Gtk-WARNING **: 22:00:12.995: Theme parsing error: xournalpp.css:51:34: Junk at end of value for transition
  ```

2021-02-23 07:11 UTC, personalizedrefrigerator commented
> Also, the inset shadow looks really weird. I think a "popover" effect would be better. For example, make the toolbox solid white (or black, depending on the theme color) with the shadow (white shadow if dark?) outside of the toolbox.

Good idea!

> The icon highlights are going to depend a lot on the theme. For example, they look terrible with my theme, as you can see.

I was modifying the icon highlights with CSS when dark mode is enabled. I'll do this for light mode, too.

> I get this error in the console on startup: 
>    ```    (xournalpp:94836): Gtk-WARNING **: 22:00:12.995: Theme parsing error: xournalpp.css:51:34: Junk at end of value for transition ```

A CSS `transition` property wasn't written correctly! Nice catch!

2021-02-23 07:28 UTC, personalizedrefrigerator commented
![image](https://user-images.githubusercontent.com/46334387/108812583-3c132880-7564-11eb-8e65-810d1c9303dc.png)
![image](https://user-images.githubusercontent.com/46334387/108813352-b5f7e180-7565-11eb-8a35-851ca036ed16.png)

2021-02-24 01:00 UTC, personalizedrefrigerator commented
@Technius I think I've made the requested changes. Thank you for the review!

2021-02-24 20:31 UTC, Technius commented
LGTM, thanks.

2021-02-24 20:31 UTC, merged