Isometric grid fix
xournalpp/xournalpp pull request #2967
Opened 2021-03-20 20:09 UTC by mjg

Fixes #2964

2021-04-03 21:54 UTC, rolandlo approved these changes
Thanks for the fix, which looks good. I also check all cases (even-even, odd-even, even-odd, odd-odd).
Minor nitpick in the commit description: `take of that extra diagonal when
needed.` (of -> off)
Could you please also fix the German spelling in the `pagetemplates.ini`? `Isometisch(es)` should be `Isometrisch(es)`. 

By the way, I have no idea why the side length of the equilateral triangles is set to 20pt = 5/18in in the `pagetemplates.ini`. If you want to change that value to something more sensible, please go ahead. It's not a big deal though, since it can easily be modified by the user.

2021-04-04 16:43 UTC, mjg commented
So far I've pushed the commit message fix ("take care of") and a few clean ups which do not change the behaviour.

The isometric grid specifies a different default in source than the ini file does. It's been like that since it's inception, which is strange. The default in source is the same as for graph paper. Alas, isometric grid has a margin and graph paper does not, so even with the same grid spacing they do not line up. Which made me look at some more parameters...

There is "rm" (roundMargin) but only "graph" obeys it. Well, kind of: `style="graph" config="m1=20,rm=1"` does not do on A4 paper what I think it is supposed to do. (Looks like a wrong shift.)

Isometric ground rounds no matter what and has a margin no matter what (as if "rm" and "m1" were hardcoded).

Speaking of which: "m1" is obeyed by "graph" only.

And the vertical line of "lined" could be an option, turning "lined" into "ruled" with "vline=72" to have the position in config.

So, the more I look at this the more I want to change and make uniform. BUT: Even just removing "r1=20" for the isomeric grid means that existing xopp-files may display differently. Unless I change the default in source to 20, of course. I'm not sure how to handle this in the interest of "stability" of the file format. Maybe postpone a larger overhaul for a new file format version?

2021-04-04 20:12 UTC, mjg commented
Turns out I was overly cautious. Existing xopp files store the extra parameters from the ini file. So I'll add another commit which removes the ini default, changing the display only for new files with isometric grid.

2021-04-04 20:19 UTC, rolandlo commented
@mjg 

I don't think that removing "r1=20" in the `pagetemplates.ini` (or replacing it with another value) means that existing xopp-files display differently than before. That value is saved in the xopp-file. 
In general I agree that the page types and parameters need a larger overhaul and this will most likely affect the file format, which may be better to do when introducing a new file format version. 

Let me remind you that you still haven't fixed the `Isometisch/Isometisches` in `pagetemplates.ini`.

2021-04-04 20:29 UTC, rolandlo requested changes

2021-04-04 20:29 UTC, rolandlo commented on ui/pagetemplates.ini
>  name[de]=Isometisch Gepunktet
```suggestion
name[de]=Isometrisch Gepunktet
```

2021-04-04 20:29 UTC, rolandlo commented on ui/pagetemplates.ini
>  name[de]=Isometisches Raster
```suggestion
name[de]=Isometrisches Raster
```

2021-04-04 20:37 UTC, rolandlo approved these changes
Ready for merge?

2021-04-04 20:43 UTC, merged

2021-04-04 20:43 UTC, rolandlo commented
Ok, thanks a lot for the fixes!