fix no autoloading journal for "filename.xopp" and "filename.xoj" problem
xournalpp/xournalpp pull request #3217
Opened 2021-07-09 22:52 UTC by VivekThazhathattil

This commit does the following:

If one were to enable journal autoloading (Edit -> Preferences -> Load/Save -> Autoloading Journals)  and if the xournalpp file corresponding to `<name>.pdf` were named `<name>.xopp`, `<name>.xoj`,  `<name>.pdf.xopp` or  `<name>.pdf.xoj`, then loading the pdf would autoload the xournalpp file as well. 

Previously it autoloaded only `<name>.pdf.xopp` and `<name>.pdf.xoj`. The default save file name is `<name>.xopp` for the latest build, so it would be good if the xournalpp file with that name autoloaded too.

2021-07-10 00:05 UTC, Technius requested changes
There's too much code duplication here. Can we simplify this by moving the candidate file paths into a vector and then using aloop?

2021-07-13 01:45 UTC, Technius reviewed
Nice work, this is much better. I just have some minor style suggestions (see below).

2021-07-13 01:45 UTC, Technius commented on src/control/Control.cpp
> +        std::vector<std::string> exts = {".xopp", ".xoj", ".pdf.xopp", ".pdf.xoj"};
```suggestion
        const std::vector<std::string> exts = {".xopp", ".xoj", ".pdf.xopp", ".pdf.xoj"};
```

2021-07-13 01:45 UTC, Technius commented on src/control/Control.cpp
> +        fs::path f;
Move this into the loop since it's only used there.

2021-07-13 01:45 UTC, Technius commented on src/control/Control.cpp
> +        for (int i = 0; i < exts.size(); i++) {
`i` is only used for `exts[i]`, so prefer the range based for loop:
```
for (const std::string& ext: exts) {
```

2021-07-13 03:17 UTC, VivekThazhathattil commented
I think it fixes #2911.

2021-07-14 21:21 UTC, Technius approved these changes
Thanks for the find. I've confirmed that this PR fixes the issue and works as intended.

2021-07-14 21:21 UTC, merged