Use `fs::path::u8string` everywhere
xournalpp/xournalpp pull request #3760
Opened 2022-01-31 09:29 UTC by danemtsov

... since conversion in `fs::path::string` is unspecified if `value_type` is not char (like on Windows).

This also fixes an "Illegal byte sequence" exception in my Clang build when using funny file names (e.g. '🌍🌎🌏🛰🚀.xopp') thrown here:
https://github.com/xournalpp/xournalpp/blob/2bea77ca5c91fb0f2dad2a4f2dec91e382eeedd5/src/core/control/settings/MetadataManager.cpp#L172
...and maybe others I haven't hit.

2022-01-31 09:31 UTC, danemtsov commented on src/core/control/settings/MetadataManager.cpp
> +    out << m->path.u8string() << "\n";
Not sure if there are any more like this though...

2022-01-31 19:06 UTC, danemtsov commented on src/core/control/settings/MetadataManager.cpp
> +    out << m->path.u8string() << "\n";
'Quoted'ness fixed; pretty sure this is the only place.

2022-02-02 18:12 UTC, danemtsov commented
> the windows console couldn't display utf-8

IMHO this shouldn't be cared about too much since, by default, stdout/stderr aren't a thing anyway in Windws GUI apps (except when launched from a shell running inside mintty, more on that maybe later in my other PR).

On the other hand 'normal' users ideally shouldn't have to install a (multi?) GB MSYS environment just to get some debug output, so either a way to direct stdout/stderr to a log file is needed (which then should be UTF-8), or we just add an action to show the console window that is created on startup and direct stdout/stderr there. And since nothing else is using this console (except the processes that Xournal++ spawns) we can also just `SetConsoleOutputCP(CP_UTF8)`, which should work well enough.

What do you think?

Regardless, this
https://github.com/xournalpp/xournalpp/blob/2bea77ca5c91fb0f2dad2a4f2dec91e382eeedd5/src/core/control/settings/MetadataManager.cpp#L172
and the reading counterpart need to be changed so that the metadata can be associated with a file whose name doesn't fit into single byte encoding.

2022-02-02 20:06 UTC, Febbe commented
> IMHO this shouldn't be cared about too much since, by default, stdout/stderr aren't a thing anyway in Windws GUI apps. (except when launched from a shell running inside mintty, more on that maybe later in my other PR).

Actually, it is a bug, that it does not connect to the calling tty like cmd or powershell :/. So it should be a thing.
But location issues in a debug output aren't really a thing.

I only wanted to explain the original reasons why we didn't choose `u8string` in the first place.
Also, we will run into trouble with c++20. We might switch to it in the near future. But then all current strings and conversions will bite us.

The `SetConsoleOutputCP(CP_UTF8)` function is not part of early windows7 / 8 / 10 versions. Aren't they?

PR looks good so far, but can you squash all your commits?

2022-02-02 20:16 UTC, Febbe commented on src/core/control/AudioController.cpp
> +        bool isRecording = this->audioRecorder->start((getAudioFolder() / data).u8string());
**Note @xournalpp/core :** 
`bool start(const std::string& filename);` should be `bool start(fs::path const& filename);`

2022-02-02 21:07 UTC, Febbe requested changes
Ok, I found some problems, which must be fixed.

2022-02-02 21:07 UTC, Febbe commented on test/unit_tests/util/PathTest.cpp
> +    EXPECT_EQ(string("/test/asdf.TXT"), b.u8string());
Either the literal must be also in u8 or b.string() must be used.

```suggestion
    EXPECT_EQ(string(u8"/test/asdf.TXT"), b.u8string());
```

This applies for all assertions.

2022-02-03 03:39 UTC, Technius commented on src/core/control/latex/LatexGenerator.cpp
> +    auto texFilePath = (Util::getLongPath(texDir) / "tex.tex").u8string();
Yes, this has to be system encoding. Should probably leave a comment about that here.

> g_shell_parse_argv
>
> command_line: The value is a file system path, using the OS encoding.

2022-02-03 03:39 UTC, Technius commented on src/core/control/xojfile/LoadHandler.cpp
> +                stroke->setAudioFilename(tempFile.u8string());
Any time there is an exception like this, we should document it with a comment or two.

Or change the method name to make it explicit: `stroke->setAudioFilenameSystemEncoding`, `stroke->setAudioFilenameU8`

2022-02-07 21:45 UTC, Febbe commented
#3785 fixes one of the above problems with utf8 paths.

2022-04-30 18:03 UTC, Febbe commented
@[danemtsov](https://github.com/danemtsov), do you plan to work on this further?

2023-03-24 19:30 UTC, closed without merging