scale small arrow heads by line length
xournalpp/xournalpp pull request #4055
Opened 2022-05-27 13:45 UTC by mjg

So far, the size of arrow heads is determined purely by the line width,
which is good for medium sized and long arrows. For very small arrows,
this leads to "interesting effects", especially for double headed
arrows.

To avoid these effects, scale the arrow head by the line length for
short arrows, i.e.: make the heads no larger than 0.4 * line length.
This suites double arrows as well, and besides, 0.4 is roughly
1 - (sqrt(5) - 1) / 2 which is the golden choice.

![nomin](https://user-images.githubusercontent.com/233215/170711635-363ef18c-807c-409d-b2d2-2ce7e5e442ee.png)
![withmin](https://user-images.githubusercontent.com/233215/170711639-7b174ef3-e6f3-41ba-98e6-e36c3d05a2ea.png)

2022-05-28 16:47 UTC, tattsan commented
I was faced with this "too large arrowhead" problem while creating a video about geometric vectors for students. So I like this PR, thank you so much!

If there is a problem, it is when the line width is large, as in the extra thick setting of the highlighter. 

![arrows-new](https://user-images.githubusercontent.com/6355486/170834706-08db97a3-7de1-445c-b0d7-e5e8b925432f.png)


If the width of the arrow is too wide and the arrow is too short, as shown in the figure, it will not look like an arrow in this PR setting. I think it would be better to make the arrowhead a little larger in this type of case.

2022-05-28 20:07 UTC, mjg commented
I tend to say we should scale the linewidth fpr short arrows ... With thick short lines, what would be a good choice for the arrow head size?

2022-05-29 01:22 UTC, Technius commented
Thanks for the PR, this significantly improves the arrow usability.

> With thick short lines, what would be a good choice for the arrow head size?

I think changing the length of the arrow head won't solve the problem. If we make the arrow head shorter, then the thickness of the stem will completely overshadow the arrow head (middle arrow in @tattsan's example). In contrast, if we make the arrow head longer, then we end up with the original situation where the arrow head is way too large so it ends up looking like a triangle (imagine the last arrow in @tattsan's example).

Perhaps also changing the angle (only on large thickness) might be an improvement? It might be a little too complicated though.
<details>
<summary>Quick mockup in gimp:</summary>
<img src="https://user-images.githubusercontent.com/1066652/170847994-bcd01f66-fe5b-48c3-8caa-3b5edf2477ed.png" width="600" />
</details>

2022-05-29 10:19 UTC, bhennion commented
The PR already greatly improves on the current behaviour, with minimal changes to the code, so that's great! I'm not sure we can find a good and simple solution for very thick highlighter strokes, but that's alright for now, I think.


To put in my two pennies worth: in the long run, I think a proper solution to ugly arrowheads wouold be to add stroke tips to the file format. Then, the user could chose, like, e.g. in Libreoffice

![Screenshot_20220529_115659](https://user-images.githubusercontent.com/17818041/170862402-b58efc5c-ae3f-415a-8a82-df797564c9bd.png)

This would allow to have clean arrow heads or tails (for instance, with a pointy end, not a round one) and solve the highlighter issue: something like this (without the overlapping artefact between the line and the head)
![Screenshot_20220529_121336](https://user-images.githubusercontent.com/17818041/170862927-368f08dd-3ed7-43b2-bb5a-407b31ea2dde.png)

 It'd also allow for curved arrows (simply any stroke, with an arrowhead added), fix #2808, make #3876 possible for arrows (see [this post](https://github.com/xournalpp/xournalpp/issues/3876#issuecomment-1055825021)), allow for proper arrow resizing, and so on.
All this, of course, goes way beyond the scope of this PR.

2022-05-30 18:19 UTC, Technius commented
To summarize, I think we all agree that the way to go with this PR is 1) scaling by line length and 2) adjusting the angle on thicker lines (e.g., with @tattsan's patch).

2023-02-28 18:09 UTC, bhennion reviewed
@mjg Do you want to add @tattsan's angle idea to this PR?
Otherwise, it's already much better than the current behaviour of master and I guess it could me merged.

2023-02-28 18:16 UTC, mjg commented
> @mjg Do you want to add @tattsan's angle idea to this PR? Otherwise, it's already much better than the current behaviour of master and I guess it could me merged.

Sorry, I missed the agreement. By force-pushing rebases I did not mean to ignore it ;-)

Yes, I can fold in the angle adjustment, or (better) put that on top. I'm more of a commit-early-commit-often-rebase-and-merge-gitter than a squasher ...

2023-03-01 20:42 UTC, mjg commented
Intermediate report: I wrapped my head around @tattsan 's patch now because the multiple "divide by fraction" and interaction between the cases and parameters triggered me to do so, and also because arrow shapes should scale properly if we scale both linewidth (thickness) and linelength by the same factor. I am rewriting everything in terms of the shape ratio linelength/thickness ("slimness").
My patch had two slimness regimes: scale the headsize ("arrowDist" in the code) linearly by thickness for slim arrows, linearly by linelength for fat arrows.
@tattsan introduced two more thresholds separating my "fat regime" into three regions where we alternate between thickness and linelength as the scale factor (with different scaling constants). Granted, one of them is only almost linear, as much as sin is between pi/6 and pi/3.
I'm not convinced those additional alternations are necessary - basically, the arrow wings should still protrude beyond the thick baseline, which is why we scale by thickness for fat arrows. We can help that effect by adjusting the angle.
Once the line is shorter than it is thick, there is not much we can do.

So, I'll spend more time on this than planned, hoping for better readibility. Codwise, spelling out the nested max/min constructs as ifs should not impact with a good compiler. max/min are just that anyways.

2023-03-04 18:12 UTC, mjg commented
Feel free to try out without the last commit and to adjust the thresholds between the slimness regimes :-)

2023-03-06 01:44 UTC, tattsan commented
I drawed the same arrows as in https://github.com/xournalpp/xournalpp/pull/4055#issuecomment-1140396860 with the new patch.

![arrows-new3](https://user-images.githubusercontent.com/6355486/223000956-06de43a6-41a3-48ec-a73b-552f66683e07.png)

2023-03-06 08:43 UTC, mjg commented
Thanks @tattsan . That's great for comparison, for checking whether it meets your needs and, potentially, for adjusting the parameters further.

2023-03-07 08:42 UTC, bhennion requested changes
Thanks for the changes!

There is a clang-format issue (we need to fix the CI apparently).

Also, I guess the constants should be named, so that one understands what 7, or 7 / 0.4 corresponds to.

2023-03-07 08:42 UTC, bhennion commented on src/core/control/tools/ArrowHandler.cpp
> +    double lineLength = sqrt(pow(c.x - this->startPoint.x, 2) + pow(c.y - this->startPoint.y, 2));
```suggestion
    double lineLength = std::hypot(c.x - this->startPoint.x, c.y - this->startPoint.y);
```

2023-03-07 08:42 UTC, bhennion commented on src/core/control/tools/ArrowHandler.cpp
> +        // arrow is not too long compared to the line length
```suggestion
        // arrow head is not too long compared to the line length
```

2023-03-07 08:42 UTC, bhennion commented on src/core/control/tools/ArrowHandler.cpp
> +	arrowDist *= sin(M_PI / 6.0) / sin(delta);
```suggestion
        // which allows to shorten the tips and keep the horizonzal distance
        arrowDist *= sin(M_PI / 6.0) / sin(delta);
```
Something's wrong with our clang-format test unit... It should have caught this.
Could you apply clang-format to your changes?

2023-03-07 17:21 UTC, mjg commented
I also commented on a false clang warning. We could use `#pragma` here (3 of them), but that seemed like overengineering things.

2023-03-10 09:11 UTC, bhennion approved these changes
Oh... I just realized I had left my review pending here. Sorry.

Just one small thing (see below) and then we'll be good to go.

2023-03-10 09:38 UTC, mjg commented
Thanks for catching the last concrete number ;)
Rebase error fixed.
I wasn't sure about the "resolve conversation" button, so I just re-pushed things.

2023-03-10 12:06 UTC, bhennion commented
Thanks a lot for the nice work!

Squashing and merging in 24 hours.

2023-03-11 12:11 UTC, merged