Add Duplicate Page option under Journal menu
xournalpp/xournalpp pull request #4313
Opened 2022-10-12 12:16 UTC by hyperupcall

closes #3831

2022-10-23 08:04 UTC, rolandlo requested changes
Thanks for the contribution. The case where `getCurrentPage()` returns `nullptr` should be taken acccount, as suggested in the code, I think. Otherwise this looks good to me.

2022-10-23 08:04 UTC, rolandlo commented on src/core/control/Control.cpp
> +    auto pageCopy = std::make_shared<XojPage>(*page);
```suggestion
    auto page = getCurrentPage();
    if (!page) {
        return;
    }
    auto pageCopy = std::make_shared<XojPage>(*page);
```

2022-10-23 11:33 UTC, rolandlo reviewed
One more change request: 
Please replace the code
https://github.com/hyperupcall/xournalpp/blob/531733db9d6211af56c9a2b447c768536024dc5f/src/core/gui/sidebar/previews/page/SidebarPreviewPages.cpp#L159-L179
by 
```cpp
control->duplicatePage();
break;
``` 
to avoid code duplication.

2022-11-04 04:53 UTC, hyperupcall commented
Sorry this took a while to get back to - made those changes :+1:

2022-11-04 05:09 UTC, rolandlo approved these changes
LGTM

Merging in 24 hours if no objections are raised.

2022-11-05 04:00 UTC, merged

2022-11-05 04:01 UTC, rolandlo commented
Thanks again for the contribution. Great to have the duplicate option in the `Journal` menu and less code duplication.