Use `std::numeric_limits` instead of macros
xournalpp/xournalpp pull request #4550
Opened 2023-01-01 09:54 UTC by hyperupcall

2023-01-01 13:48 UTC, rolandlo requested changes
Can you please apply "Include what you use" for the `<liimts>` header in the sense of https://include-what-you-use.org/ ? For instance it is currently neither included in `EditSelectionContents.cpp` nor `EditSelectionContents.h`.

Otherwise LGTM.

2023-01-02 05:57 UTC, hyperupcall commented
Sorry about that - fixed now

2023-01-02 08:41 UTC, rolandlo approved these changes
I have one minor nitpick. Could you please squash the commits then into one and rebase on current master afterwards?

2023-01-02 08:41 UTC, rolandlo commented on src/core/plugin/Plugin.cpp
> +#include <limits>     // for numeric_limits
Already included in `Plugin.h`
```suggestion
```

2023-01-06 09:45 UTC, hyperupcall commented
:+1:

2023-01-06 09:49 UTC, rolandlo approved these changes
LGTM. 
Squashing and merging in 24 hours if no objections are raised.

2023-01-07 18:06 UTC, merged

2023-01-07 18:07 UTC, rolandlo commented
Thanks for this PR as well! Always good to improve consistency.