Use view::Mask for buffers -- Improve performances
xournalpp/xournalpp pull request #4687
Opened 2023-02-28 06:12 UTC by bhennion

This PR makes use of view::Mask for the PageView::buffer, as well as for the mask in ErasableStrokeView and the cache in PdfCache.

It also uses `cairo_surface_create_similar()` instead of `cairo_image_surface_create()` for those surface, thus using the most suitable Cairo backend available. This should improve performances (closes #4179).
The emoji part of #3692 is also fixed, and the issue underlying #4555 (ugly-fixed with #4566) is cleaned up: no more unsuitable use of `cairo_surface_set_device_scale()`.

The 3 commits are self contained and can be reviewed separately.

2023-02-28 06:17 UTC, bhennion commented
This needs some decent amount of testing, as this affects the very base of our rendering system.
In particular, it'd be nice to know if this indeed improve performances, especially on MacOS: it should now be using Quartz surfaces instead of image surfaces.

2023-02-28 08:55 UTC, rolandlo commented
It's very hard to tell if the PR improves performance or not. The performance is already pretty good in master. I need a bit of input stabilization for my Wacom tablet on MacOS, but then it feels completely smooth. 
Is there a way to measure performance?

What I can say though is that on MacOS image surfaces are used with this PR, not Quartz surfaces (and I guess rightly so reading issues on the Gtk tracker):
```term
Creating mask of type: image
  Its size: 1197 x 1693 (in device space)
  Its DPI scaling: 2 x 2
```

One thing that I have noticed (already on master though): Drawing at 700% zoom is smooth (on MacOS) now as well. Not sure when that changed.

2023-02-28 13:26 UTC, bhennion commented
If it does not change the surface type, then there is no reason to expect a performance improvement.

About performance measurement, all I have for now is the kind of X11 benchmarks I mentioned in other posts. Nothing on MacOS.

Anyway, it's very good that MacOS' version is now viable! :-)

2023-03-09 09:59 UTC, rolandlo commented
I'm running into some issues when executing via
```term
GDK_BACKEND=x11 GDK_SCALE=2 ./xournalpp 
```

The first time I got a hard crash (while erasing with the stylus button), after which I could only reboot the computer.

The second time I got a crash and this message (while using filled highlighter with the mouse): 

```term
(xournalpp:13750): Gdk-ERROR **: 10:53:40.201: The program 'xournalpp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadLength (poly request too large or internal Xlib length erro'.
  (Details: serial 12765 error_code 16 request_code 138 (RENDER) minor_code 4)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

It will need more to investigate whether these crashes also happen with master or only with the PR.

2023-03-09 11:28 UTC, rolandlo commented
I'm getting more such crashes, when running `./xournalpp` in a x11 session:

```
(xournalpp:25179): Gdk-ERROR **: 12:26:52.088: The program 'xournalpp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 21316 error_code 9 request_code 139 (RENDER) minor_code 4)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

2023-03-09 13:37 UTC, bhennion commented
Uh... I've tried to reproduce without success so far. I'm guessing this comes from using `xlib` surfaces in cairo.
The 3 error logs you posted actually report 3 different error codes. Have you noticed any sort of behaviour that seems to be triggering (any one of) them? e.g. the presence on the document of a certain kind of element? Does it happen often for you?

2023-03-09 13:47 UTC, rolandlo commented
Here is one more (different error code again) while erasing:
```term
(xournalpp:37672): Gdk-ERROR **: 14:45:59.650: The program 'xournalpp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 36584 error_code 3 request_code 1 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

2023-03-09 13:52 UTC, rolandlo commented
Wait, I might have checked out the wrong commit (after doing the bisection). Everything I said might not apply to this PR.

2023-03-09 14:18 UTC, rolandlo commented
Even after making sure the right commit gets compiled and compiling new, renaming the `settings.xml` I still get those crashes. They (or at least most of them) seem to be tied to the eraser. In fact when I start with `GDK_BACKEND=x11 ./xournalpp`, as soon as I switch to the eraser and click the mouse button (when using the mouse) or touch the screen with the stylus tip (when using the stylus button) the crash happens.
I will try to find out which of the 3 commits is the problematic one.

2023-03-09 14:22 UTC, rolandlo commented
It's the first of the three commits (8085e81d2a48e7ef24fb5bc5496049d887474d2a) that is causing the issue.

2023-03-09 14:46 UTC, bhennion commented
Still can't reproduce. Have you tried running with `GDK_SYNCHRONIZE` set as the error messages suggest (to get a better trace)?

2023-03-09 14:52 UTC, rolandlo commented
If I run via `GDK_BACKEND=x11 GDK_SYNCHRONIZE=on ./xournalpp` then I get the message:

```term
Xlib: sequence lost (0x1686d > 0x686e) in reply type 0x0!
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
xournalpp: ../../src/xcb_io.c:730: _XReply: Zusicherung »!xcb_xlib_threads_sequence_lost« nicht erfüllt.

** (xournalpp:8265): WARNING **: 15:49:16.156: [Crash Handler] Crashed with signal 6

** (xournalpp:8265): WARNING **: 15:49:16.156: [Crash Handler] Wrote crash log to: /home/roland/.cache/xournalpp/errorlogs/errorlog.20230309-154916.log

** (xournalpp:8265): WARNING **: 15:49:16.366: Versuche eine Notfall-Speicherung des aktuell geöffneten Dokuments…

** (xournalpp:8265): WARNING **: 15:49:16.366: Dokument erfolgreich nach "/home/roland/.config/xournalpp/emergencysave.xopp" gespeichert.
```

Errorlog:
```term
Error: signal 6
[bt]: (0) ./xournalpp(+0x38e13c) [0x562da659613c]
[bt]: (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3bcf0) [0x7f5232a3bcf0]
[bt]: (2) /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x11b) [0x7f5232a9226b]
[bt]: (3) /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x16) [0x7f5232a3bc46]
[bt]: (4) /lib/x86_64-linux-gnu/libc.so.6(abort+0xd7) [0x7f5232a227fc]
[bt]: (5) /lib/x86_64-linux-gnu/libc.so.6(+0x2271b) [0x7f5232a2271b]
[bt]: (6) /lib/x86_64-linux-gnu/libc.so.6(+0x33596) [0x7f5232a33596]
[bt]: (7) /lib/x86_64-linux-gnu/libX11.so.6(_XReply+0x486) [0x7f52330cb356]
[bt]: (8) /lib/x86_64-linux-gnu/libX11.so.6(XSync+0x4f) [0x7f52330be5df]
[bt]: (9) /lib/x86_64-linux-gnu/libX11.so.6(+0x3967f) [0x7f52330be67f]
[bt]: (10) /lib/x86_64-linux-gnu/libX11.so.6(XSetInputFocus+0x68) [0x7f52330bab68]
[bt]: (11) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x69aa6) [0x7f5233761aa6]
[bt]: (12) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x6824f) [0x7f523376024f]
[bt]: (13) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x711b9) [0x7f52337691b9]
[bt]: (14) /lib/x86_64-linux-gnu/libgdk-3.so.0(gdk_display_get_event+0x89) [0x7f523372ea79]
[bt]: (15) /lib/x86_64-linux-gnu/libgdk-3.so.0(+0x71546) [0x7f5233769546]
[bt]: (16) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x299) [0x7f5233341569]
[bt]: (17) /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xab3c8) [0x7f52333963c8]
[bt]: (18) /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x30) [0x7f523333ed20]
[bt]: (19) /lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x1dd) [0x7f523359645d]
[bt]: (20) ./xournalpp(_ZN11XournalMain3runEiPPc+0x785) [0x562da659d950]
[bt]: (21) ./xournalpp(main+0x29) [0x562da6595fa2]
[bt]: (22) /lib/x86_64-linux-gnu/libc.so.6(+0x23510) [0x7f5232a23510]
[bt]: (23) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7f5232a235c9]
[bt]: (24) ./xournalpp(_start+0x25) [0x562da6595eb5]
```

2023-03-09 14:55 UTC, rolandlo commented
When running that way, the app more often than not already crashes at startup:

```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
xournalpp: ../../src/xcb_io.c:278: poll_for_event: Zusicherung »!xcb_xlib_threads_sequence_lost« nicht erfüllt.

** (xournalpp:8612): WARNING **: 15:53:58.114: [Crash Handler] Crashed with signal 6

```

2023-03-09 15:15 UTC, bhennion commented
Alright... So, I can not reproduce your error messages, but I actually realized the use of xlib surfaces is **slower** on my machine (typically, when using the eraser on a filled highlighter stroke).
I (rebased on master and) committed a hack so that we always use a cairo_image_surface. This is in the end less laggy on my laptop... Does this also fix your errors?

If so, I'll clean this all up and bury once and for all the `gdk_window_create_similar_surface` (which gets us `xlib` surfaces). It seems is only brings bad news (despite the very positive benchmarking I had with `xlib` surfaces, but the benchmark relied on direct FB rendering and did not rely on GDK/GTK at all).

2023-03-09 15:23 UTC, rolandlo commented
Yes, with the removal of similar surfaces (last commit) the crashes don't occur anymore.

2023-03-11 19:57 UTC, bhennion commented
Alright, I cleaned up the thing. This PR is now solely a code cleanup/refactor to use view/Mask as a buffer or a mask everywhere we use such a buffer or mask. No drastic changes in performances are to be expected.

2023-03-15 07:44 UTC, rolandlo commented
Suggested edit:
```diff
diff --git a/src/core/control/jobs/RenderJob.cpp b/src/core/control/jobs/RenderJob.cpp
index d4cd500d3..33d61a6ec 100644
--- a/src/core/control/jobs/RenderJob.cpp
+++ b/src/core/control/jobs/RenderJob.cpp
@@ -40,7 +40,7 @@ void RenderJob::rerenderRectangle(Rectangle<double> const& rect) {
 
     Range maskRange(rect);
     maskRange.addPadding(RENDER_PADDING);
-    xoj::view::Mask newMask(maskRange, view->xournal->getZoom(), view->xournal->getDpiScaleFactor(),
+    xoj::view::Mask newMask(view->xournal->getDpiScaleFactor(), maskRange, view->xournal->getZoom(),
                             CAIRO_CONTENT_COLOR_ALPHA);
 
     renderToBuffer(newMask.get());
@@ -62,8 +62,9 @@ void RenderJob::run() {
     this->view->repaintRectMutex.unlock();
 
     if (rerenderComplete) {
-        xoj::view::Mask newMask(Range(0, 0, view->page->getWidth(), view->page->getHeight()), view->xournal->getZoom(),
-                                view->xournal->getDpiScaleFactor(), CAIRO_CONTENT_COLOR_ALPHA);
+        xoj::view::Mask newMask(view->xournal->getDpiScaleFactor(),
+                                Range(0, 0, view->page->getWidth(), view->page->getHeight()), view->xournal->getZoom(),
+                                CAIRO_CONTENT_COLOR_ALPHA);
 
         renderToBuffer(newMask.get());
         {
@@ -83,15 +84,14 @@ static void repaintWidgetArea(GtkWidget* widget, int x1, int y1, int x2, int y2)
     Util::execInUiThread([=]() { gtk_xournal_repaint_area(widget, x1, y1, x2, y2); });
 }
 
-void RenderJob::repaintPage() const {
-    repaintPageArea(0, 0, view->getWidth(), view->getHeight());
-}
+void RenderJob::repaintPage() const { repaintPageArea(0, 0, view->getWidth(), view->getHeight()); }
 
 void RenderJob::repaintPageArea(double x1, double y1, double x2, double y2) const {
     double zoom = view->xournal->getZoom();
     int x = view->getX();
     int y = view->getY();
-    repaintWidgetArea(view->xournal->getWidget(), x + std::floor(zoom * x1), y + std::floor(zoom * y1), x + std::ceil(zoom * x2), y + std::ceil(zoom * y2));
+    repaintWidgetArea(view->xournal->getWidget(), x + std::floor(zoom * x1), y + std::floor(zoom * y1),
+                      x + std::ceil(zoom * x2), y + std::ceil(zoom * y2));
 }
 
 void RenderJob::renderToBuffer(cairo_t* cr) const {
diff --git a/src/core/view/Mask.cpp b/src/core/view/Mask.cpp
index 66af4d9b4..a953b0a2f 100644
--- a/src/core/view/Mask.cpp
+++ b/src/core/view/Mask.cpp
@@ -29,7 +29,7 @@ Mask::Mask(cairo_surface_t* target, const Range& extent, double zoom, cairo_cont
     constructorImpl(target, extent, zoom, contentType);
 }
 
-Mask::Mask(const Range& extent, double zoom, int DPIScaling, cairo_content_t contentType):
+Mask::Mask(int DPIScaling, const Range& extent, double zoom, cairo_content_t contentType):
         xOffset(static_cast<int>(std::floor(extent.minX * zoom))),
         yOffset(static_cast<int>(std::floor(extent.minY * zoom))),
         zoom(zoom) {
diff --git a/src/core/view/Mask.h b/src/core/view/Mask.h
index cffa26979..7edfe3d3f 100644
--- a/src/core/view/Mask.h
+++ b/src/core/view/Mask.h
@@ -39,13 +39,13 @@ public:
 
     /**
      * @brief Create a mask tailored for the specified target
+     * @param DPIScaling The DPI scaling of the targeted use monitor
      * @param extent The extent of the mask, in local coordinates (i.e. in the coordinates of the cairo context(s) on
      * which the mask will be used).
      * @param zoom The local zoom ratio (zoom ratio of the cairo context(s) on which the mask will be used).
-     * @param DPIScaling The DPI scaling of the targeted use monitor
      * @param contentType The intended content of the mask
      */
-    Mask(const Range& extent, double zoom, int DPIScaling, cairo_content_t contentType = CAIRO_CONTENT_ALPHA);
+    Mask(int DPIScaling, const Range& extent, double zoom, cairo_content_t contentType = CAIRO_CONTENT_ALPHA);
 
     cairo_t* get();
     bool isInitialized() const;
@@ -76,8 +76,8 @@ public:
     inline double getZoom() const { return zoom; }
 
 private:
-    template <typename TargetType>
-    void constructorImpl(TargetType target, const Range& extent, double zoom, cairo_content_t contentType);
+    template <typename DPIInfoType>
+    void constructorImpl(DPIInfoType dpiInfo, const Range& extent, double zoom, cairo_content_t contentType);
 
     xoj::util::CairoSPtr cr;
     int xOffset = 0;

```

2023-03-15 17:13 UTC, rolandlo requested changes
Thanks for this very nice refactoring, which makes the use of buffers throughout the code much cleaner. There is one thing that needs to be fixed though: `DEBUG_ERASABLE_STROKE` mode. Turning that flag on currently doesn't compile (see suggested fix in the code). I'm not quite sure what I should see there, so please make sure it works as intended.
Otherwise I haven't found any regressions in my testing (on Linux, Windows and MacOS). Performance looks still pretty much the same (which is fine). There are also some nitpicks that I would like you to consider, among them two unused functions. 

I have found an issue unrelated to this PR (with TeXDialog background color) while testing, so I will open an issue about it.

2023-03-15 20:22 UTC, bhennion commented on src/core/gui/PageView.cpp
> +auto XojPageView::getLastVisibleTime() -> long {
I did as you suggested. Nice catch!

2023-03-15 20:30 UTC, bhennion commented
Thanks for the review!
I fixed the DEBUG_ERASABLE_STROKE_BOXES mode. What you should see are bounding boxes of various colors when cutting a self-intersecting highlighter stroke (I don't remember the color code).
Those boxes represent bounding boxes of lines segments, which are stored in a binary tree. They are used to find the areas where the stroke self-intersects and repaint them if necessary when the stroke is cut in half.

2023-03-15 20:40 UTC, bhennion commented
Mmm... The clang-format version used in the check seems to differ from mine (15.0.7).

2023-03-15 21:03 UTC, rolandlo commented
Suggested edit:
```diff
diff --git a/src/core/gui/PageView.h b/src/core/gui/PageView.h
index f0da0d6cb..cc6b36754 100644
--- a/src/core/gui/PageView.h
+++ b/src/core/gui/PageView.h
@@ -50,7 +50,7 @@ class XojPdfPage;
 namespace xoj::view {
 class OverlayView;
 class ToolView;
-}
+}  // namespace xoj::view
 
 class XojPageView: public LegacyRedrawable, public PageListener, public xoj::view::Repaintable {
 public:
@@ -131,12 +131,6 @@ public:
     GdkRGBA getSelectionColor() override;
     bool hasBuffer() const;
 
-    /**
-     * 0 if currently visible
-     * -1 if no image is saved (never visible or cleanup)
-     * else the time in Seconds
-     */
-    long getLastVisibleTime();
     TextEditor* getTextEditor();
 
     /**
diff --git a/src/core/gui/XournalView.cpp b/src/core/gui/XournalView.cpp
index 674408b56..973b3881f 100644
--- a/src/core/gui/XournalView.cpp
+++ b/src/core/gui/XournalView.cpp
@@ -106,12 +106,6 @@ XournalView::~XournalView() {
     this->handRecognition = nullptr;
 }
 
-void XournalView::staticLayoutPages(GtkWidget* widget, GtkAllocation* allocation, void* data) {
-    auto* xv = static_cast<XournalView*>(data);
-    xv->layoutPages();
-}
-
-
 auto XournalView::clearMemoryTimer(XournalView* widget) -> gboolean {
     widget->cleanupBufferCache();
     return true;
diff --git a/src/core/gui/XournalView.h b/src/core/gui/XournalView.h
index 743d068c8..3419dd390 100644
--- a/src/core/gui/XournalView.h
+++ b/src/core/gui/XournalView.h
@@ -154,8 +154,6 @@ private:
 
     void cleanupBufferCache();
 
-    static void staticLayoutPages(GtkWidget* widget, GtkAllocation* allocation, void* data);
-
 private:
     /**
      * Scrollbars

```

2023-03-15 21:10 UTC, bhennion commented
Oh, right sorry. I missed your comment about `staticLayoutPages`. Thanks!

2023-03-15 21:21 UTC, rolandlo approved these changes
LGTM!

2023-03-18 12:41 UTC, merged