Issue #4642 configure tab size
xournalpp/xournalpp pull request #4752
Opened 2023-03-20 12:03 UTC by CruzeBlade

Hi, 

I added a new preference for the tab size.
Instead of using a tabular char, the user can select to insert spaces instead.
Also, the amount of spaces to be inserted can be configured, in the range of 1 - 8. 
For efficiency reasons, I wouldn't allow inserting any more characters with a single stroke. 

I have currently located this preference under "Preferences > Input System > Tab". 
I'm not very happy about that location, but couldn't find something more intuitive.
In the future, a preference page "Controls" (or something like this) would be good.

Solves #4642.

2023-03-20 19:07 UTC, jhilmer requested changes

2023-03-20 19:49 UTC, CruzeBlade commented on src/core/gui/dialog/SettingsDialog.cpp
> +    gtk_spin_button_set_value(sbNumberOfSpacesForTab, settings->getNumberOfSpacesForTab());
I'm not sure, but is the value not already limited by the GtkAdjustment "adjustmentNumberOfSpacesForTab"?
Otherwise, I will add this, of course.

2023-03-20 19:56 UTC, jhilmer commented
I would have preferred a separate commit with the clang-format changes.

2023-03-20 20:00 UTC, CruzeBlade commented
> I would have preferred a separate commit with the clang-format changes.

Sorry, but the clang-format happened automatically without me noticing it. Should I revert the commit?

2023-03-20 20:08 UTC, jhilmer commented
Not needed for me. But it looks like it need to be rebased on master.

2023-03-21 20:49 UTC, CruzeBlade commented
Ok, I have rebased. Anything else I need to do?

2023-05-19 06:53 UTC, CruzeBlade commented
Hi, would be great if this could be merged. Or do I still need to change / improve something?

2023-07-30 09:21 UTC, CruzeBlade commented
Hi @rolandlo, Hi @bhennion 

I would appreciate, if you could take a look at this PR. It appears that it has not received any attention for quite some time.

I completely understand the demands on your time, so please don't feel rushed. I am patient and willing to wait for a response. However, any feedback or guidance you could provide would be immensely helpful.

Thank you for your attention, and I look forward to hearing from you soon.

2023-08-03 06:41 UTC, rolandlo requested changes
Thanks for the contribution and sorry for the long wait.
The feature looks good to me and works fine. I would like to suggest two changes to the settings GUI:
- Can you please put the "Number of Spaces: " and spinbox onto the same line like the checkbox? That would look more consistent with the rest of the settings dialog.
- When the "Indent using spaces" checkbox is disabled, the "Number of Spaces" part should be grayed out.

2023-08-15 09:47 UTC, CruzeBlade commented
I have changed the UI as suggested:

![demo_spaces_as_tab](https://github.com/xournalpp/xournalpp/assets/37212628/3d93c1ca-33ee-4007-bc3c-51f17bd932af)

Does it look like you expected it?

2023-08-15 09:57 UTC, rolandlo commented
> I have changed the UI as suggested:
> 
> ![demo_spaces_as_tab](https://user-images.githubusercontent.com/37212628/260679308-3d93c1ca-33ee-4007-bc3c-51f17bd932af.gif)
> 
> Does it look like you expected it?

Yes, that's how I expected it.

2023-08-16 03:21 UTC, rolandlo reviewed
It works all fine now. Could you reduce the large diff to the `settings.glade` file though? Only your UI changes should result in changes to that file, not some formatting changes or the use of a different glade version.

Note to self: The content of b5055ab7e48e134997adbfa4024de817dbfeacfb could be simplified using `SettingsDialog::enableWithEnabledCheckbox` from (unmerged) PR #4855.

2023-10-14 16:52 UTC, CruzeBlade commented
@rolandlo I would really appreciate it if this could get merged anytime soon.

2023-10-15 09:37 UTC, CruzeBlade commented on src/core/control/settings/Settings.h
> +constexpr int MAX_SPACES_FOR_TAB = 8;
I have changed it as suggested.

2023-10-15 09:37 UTC, CruzeBlade commented on src/core/gui/dialog/SettingsDialog.cpp
> +    gtk_widget_set_sensitive(gtk_widget_get_parent(GTK_WIDGET(sbNumberOfSpacesForTab)), settings->getUseSpacesAsTab());
I have changed it as suggested.

2023-10-15 09:39 UTC, CruzeBlade commented on src/core/gui/dialog/SettingsDialog.cpp
> +    gtk_spin_button_set_value(sbNumberOfSpacesForTab, settings->getNumberOfSpacesForTab());
I'm not sure if this cast is still necessary, because ```settings->getNumberOfSpacesForTab()``` is now an unsigned int already.

2023-10-15 09:39 UTC, CruzeBlade commented on src/core/gui/dialog/SettingsDialog.cpp
> +            gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(builder.get("sbNumberOfSpacesForTab"))));
I have changed it as suggested.

2023-10-15 09:39 UTC, CruzeBlade commented on src/core/control/settings/Settings.h
> +    bool getUseSpacesAsTab();
I have changed it as suggested.

2023-10-15 09:40 UTC, CruzeBlade commented on src/core/control/settings/Settings.cpp
> +}
I hope it's fine now?

2023-10-15 09:43 UTC, CruzeBlade commented on src/core/control/settings/Settings.h
> +    unsigned int numberOfSpacesForTab{};
Hi, thank you for the review. I appreciate it. I have implemented most of the requested changes. Let me know if everything is okay now.

2023-10-17 10:51 UTC, rolandlo commented on src/core/gui/dialog/SettingsDialog.cpp
> +    gtk_spin_button_set_value(sbNumberOfSpacesForTab, settings->getNumberOfSpacesForTab());
No, it's not necessary any more.

2023-10-17 10:52 UTC, rolandlo approved these changes
LGTM

Merging in 24 hours if no objections are raised.

2023-10-17 10:53 UTC, rolandlo commented
Ah well, can't merge until @bhennion approves.

2023-10-18 04:46 UTC, merged

2023-10-18 04:48 UTC, rolandlo commented
Thanks @CruzeBlade for this useful feature. I just merged it.

2025-10-29 18:22 UTC, quantenzitrone commented
hi, was this removed in the gtk4 rewrite?

2025-10-30 07:29 UTC, bhennion commented
> hi, was this removed in the gtk4 rewrite?

I don't think it has been removed (or at least not intentionally). Why the question? Does it not work on the GTK4 branch?

2025-11-08 21:18 UTC, quantenzitrone commented
> I don't think it has been removed (or at least not intentionally). Why the question? Does it not work on the GTK4 branch?

i am dumb and thought gtk4 was merged into master because i saw some pretty big changes since i last use xournalpp
however i can't find the setting in 1.2.8