Enhances Scrolling outside the page
xournalpp/xournalpp pull request #4855
Opened 2023-05-03 15:43 UTC by p0mm

## Solution for FR #2300 
additional space left, right, above or below the pages can be added separately 
you can find this under 'Preferences -> Drawing Area -> Scrolling outside the page'

## this is a first trivial solution, i still plan to: 

- [ ] make the user interface easier and more intuitive so that the user is able to understand the options available to them instantly
- [ ] ensure adding horizontal/vertical space on both sides is still possible as easily as before 
- [ ] make sure people don't need to change their settings if they have done this 
- [ ] allow the user to add the space of one page (to imitate infinite scrolling)
- [ ] ensure my logic is represented in the code and easily understandable

2023-05-23 18:53 UTC, tattsan commented
Hi!  I started to use this enhancement, and I like it. There's one question:
What units are used in the references menu?
I've set 200 for upper additional space, then
* On 140dpi tablet, the space seems to have about 40mm height.
* On 212dpi tablet, the space seems to have about 25mm height.

2023-05-23 19:09 UTC, tattsan commented
Ah this looks like the number of dots, is that correct? ( sorry, I haven't seen the code yet. )
If so, it would be nice if it was displayed as "200dots" in the menu.

2023-05-24 11:39 UTC, p0mm commented
Hey, I'm glad you like it!
The unit should be pixels? Not sure if that is different then dots actually
A unit should definitely be mentioned in the menu though - I'll make sure to add that!
Thank you a lot for trying it out!

2023-05-29 14:13 UTC, p0mm commented
I made a whole new sentence to add information about the unit, I am not sure if that might be to much, but adding it to the sentence that describes the setting felt very forced & now you can at least tell the unit very easily?
Here it is:
![Scroll_past_end_setting_new](https://github.com/xournalpp/xournalpp/assets/125290879/7f560fc4-679e-406a-bc7b-aafef19dd6bf)

2023-05-31 01:10 UTC, tattsan commented
Thank you for responding to my request. I think the added text is concise, clear and easy to understand.

2023-06-14 17:50 UTC, p0mm commented
### i added an option for Unlimited Scrolling!
- you can now scroll as much as you want -> even until the pages are not longer visible
- this option can be found as an alternative to adding customizable space for scrolling 
![Unlimited_Scrolling](https://github.com/xournalpp/xournalpp/assets/125290879/449559a9-aa24-4336-a817-b8bce96915ce)
- xournalpp will not forget the custom settings, you can turn back to them any time
[video demo of unlimited scrolling :)](https://github.com/xournalpp/xournalpp/assets/125290879/c2e5167e-81be-4036-8537-dc425a1e718f)

-> i have now done everything  i wanted to do in this PR! :D

2023-07-22 15:18 UTC, p0mm commented
This PR has been finished on my part for quite some time.
I would be really happy about a review :) @rolandlo @Technius

2023-08-09 05:24 UTC, rolandlo requested changes
Thanks for this valuable contribution. The feature looks useful, the settings dialog looks pretty nice and the code is quite clean. There is one thing that disturbs me in the code and that is the twofold `sumIf`. That would look more readable if you made a case distinction between having unlimited scrolling or not. In both cases there is only one `sumif`.
Also please rebase on current master and solve the merge conflict.

2023-08-09 05:24 UTC, rolandlo commented on src/core/gui/Layout.cpp
> +            sumIf(sumIf(2 * XOURNAL_PADDING,
twofold `sumif`

2023-08-09 05:24 UTC, rolandlo commented on src/core/gui/Layout.cpp
> +            sumIf(sumIf(2 * XOURNAL_PADDING,
here too

2023-08-09 05:24 UTC, rolandlo commented on src/core/gui/Layout.cpp
> +    auto const v_padding = sumIf(sumIf(XOURNAL_PADDING, settings->getAddVerticalSpaceAmountAbove(),
here too

2023-08-09 05:24 UTC, rolandlo commented on src/core/gui/Layout.cpp
> +    auto const h_padding = sumIf(sumIf(XOURNAL_PADDING, settings->getAddHorizontalSpaceAmountLeft(),
here too

2023-08-09 05:24 UTC, rolandlo commented on src/core/gui/Layout.cpp
> +    auto const paddingAbove = sumIf(sumIf(XOURNAL_PADDING, settings->getAddVerticalSpaceAmountAbove(),
here too

2023-08-09 05:24 UTC, rolandlo commented on src/core/gui/Layout.cpp
> +    auto paddingBefore = sumIf(sumIf(XOURNAL_PADDING, settings->getAddHorizontalSpaceAmountLeft(),
here too

2023-08-16 09:59 UTC, p0mm commented
Thank you so much for the review! 
I got rid of the sumIf's & rebased on current master :)

2023-08-16 14:49 UTC, rolandlo approved these changes
LGTM!

We have to clarify how we deal with conflicts in the `settings.glade` with #4796 Who goes first/who solves the conflicts?
@bhennion What's your take on this?

2023-08-17 13:40 UTC, bhennion commented
> LGTM!
> 
> We have to clarify how we deal with conflicts in the `settings.glade` with #4796 Who goes first/who solves the conflicts? @bhennion What's your take on this?

I think its alright. I'll be able to rebase onto this and redo the changes Copy-pasting via Glade.

2023-08-18 19:58 UTC, merged

2023-08-18 19:58 UTC, rolandlo commented
Thanks again @p0mm for this enhancement. I just merged it.

2023-08-19 20:03 UTC, p0mm commented
Very happy to see this merged!
Sorry for not being very responsive, i'm a bit busy at the moment.
Thank you both so much for your work!! @bhennion @rolandlo