Merge back Release 1.2.1
xournalpp/xournalpp pull request #5090
Opened 2023-08-24 20:47 UTC by rolandlo

I'm not sure if I did it right with the merge, since I had trouble with the release-helper script (for the merge back step) and did it manually. The total diff should be mostly fine. The changes to the glade file must be fixed though. 
Is the commit tree alright?

2023-08-25 05:17 UTC, bhennion requested changes
The assert()'s need to become xoj_assert()'s. I did not check the .glade file yet. Do you want me to have a look?

2023-08-25 05:17 UTC, bhennion commented on src/core/gui/inputdevices/PenInputHandler.cpp
> +#include <cassert>    // for assert
```suggestion
#include "util/Assert.h"  // for xoj_assert
```
(+ associated clang-formatting)

2023-08-25 05:17 UTC, bhennion commented on src/core/gui/inputdevices/PenInputHandler.cpp
> +        assert(pressureMode == PressureMode::DEVICE_PRESSURE);
```suggestion
        xoj_assert(pressureMode == PressureMode::DEVICE_PRESSURE);
```

2023-08-25 05:17 UTC, bhennion commented on src/core/gui/inputdevices/PenInputHandler.cpp
> +    assert(settings->getMinimumPressure() >= 0.01);
```suggestion
    xoj_assert(settings->getMinimumPressure() >= 0.01);
```

2023-08-25 05:36 UTC, rolandlo commented
> The assert()'s need to become xoj_assert()'s. 

Right!

> I did not check the .glade file yet. Do you want me to have a look?

Yes, please! Something with the `GtkAlignment`s seems wrong.

2023-08-25 09:10 UTC, bhennion commented
> Yes, please! Something with the `GtkAlignment`s seems wrong.

It was a mess indeed. I corrected it and forced pushed. (I did not take care of the assert() though)

2023-08-26 04:49 UTC, rolandlo commented
Should commit [1ac6814](https://github.com/xournalpp/xournalpp/pull/5090/commits/1ac68146637660708837661f9c357f56f9777d55) be really part of the merge? In #4455 we didn't have the version bump commit included.

2023-08-27 09:09 UTC, bhennion commented on ui/settings.glade
> +                                <property name="can-focus">False</property>
I f'ed up the indentation here:
```suggestion
                                <property name="visible">True</property>
                                <property name="can-focus">False</property>
```

2023-08-27 09:10 UTC, bhennion commented
> Should commit [1ac6814](https://github.com/xournalpp/xournalpp/pull/5090/commits/1ac68146637660708837661f9c357f56f9777d55) be really part of the merge? In #4455 we didn't have the version bump commit included.

I don't know. It seems odd to me to take a commit out. @xournalpp/core what's the procedure here?

2023-08-27 09:41 UTC, Febbe commented
Master requires a different version bump, therefore, it would be fine to leave that commit out. But we can also override it in the merge commit. Probably this is cleaner for the history. We will get merge conflicts any way.

2023-08-28 05:02 UTC, rolandlo commented
In https://github.com/xournalpp/xournalpp/pull/3599#issuecomment-975509184 when merging back release 1.1.1 @LittleHuba requested to drop the version bump commit which would correspond to https://github.com/xournalpp/xournalpp/pull/5090/commits/eb070c46acb9badbd22635976aeffe97c1defbbf here. @LittleHuba can you explain, which version bump commits should be included and which shouldn't and for what reason?
Also how would I drop a commit in this merge (preferably without solving all merge conflicts again)? Using `git rebase -i --rebase-merges` ?

2023-08-30 06:47 UTC, rolandlo commented
I have dropped the version bump commit to `1.2.2~dev` as outlined above and have fixed the indentation in the `.glade` file. From my side I would suggest to merge this from the CLI (with `ff-only`).

2023-08-30 08:08 UTC, bhennion approved these changes

2023-08-30 09:04 UTC, merged

2023-09-24 20:48 UTC, LittleHuba commented
> In https://github.com/xournalpp/xournalpp/pull/3599#issuecomment-975509184 when merging back release 1.1.1 @LittleHuba requested to drop the version bump commit which would correspond to https://github.com/xournalpp/xournalpp/pull/5090/commits/eb070c46acb9badbd22635976aeffe97c1defbbf here. @LittleHuba can you explain, which version bump commits should be included and which shouldn't and for what reason?
> ~Also how would I drop a commit in this merge (preferably without solving all merge conflicts again)? Using `git rebase -i --rebase-merges` ?~
> 
> For the record: I can drop the last version bump commit using 
> ```term
> git rebase -i -r -X ours HEAD~<number of commits>
> git diff -R origin/<branchname> | git apply
> ``` 
> followed by amending the changes.
> 

Hi
Sorry that was way too long ago for me to remember in detail. I think the request came originally from a user. You could check out the last version bump PR for comments.