Remember widget visibility in default view mode
xournalpp/xournalpp pull request #5130
Opened 2023-09-08 10:14 UTC by tmoerschell

Fix for issue #5127
Remove unused code and remember visibility of widgets (menubar, toolbar, sidebar) by saving it to the settings
The changes are also persistent between sessions since they are saved to the settings

2023-09-13 13:45 UTC, bhennion requested changes
Thanks for the PR and for fixing this regression. I have a couple of comments below.
Also, the class FullscreenHandler is really not useful anymore (it has only one member variable `bool fullscreen` whose getter is only used in Control::isFullscreen() which in turn is never used).
I think you could simply remove FullscreenHandler entirely and implement a MainWindow::goFullscreen(bool) calling the gtk functions.

2023-09-13 18:09 UTC, tmoerschell commented on src/core/control/settings/Settings.cpp
> +}
Fixed in [15b2786](https://github.com/xournalpp/xournalpp/pull/5130/commits/15b2786fab9e7ea2159228344e64441c56b5a812)

2023-09-13 18:12 UTC, tmoerschell commented on src/core/gui/MainWindow.cpp
> +    if (!settings->isFullscreen() && !settings->isPresentationMode()) {
Done in [4bb4d44](https://github.com/xournalpp/xournalpp/pull/5130/commits/4bb4d4466e19e2cbb853fcf8c36fedb478a743a7)

2023-09-13 18:12 UTC, tmoerschell commented on src/core/gui/MainWindow.cpp
> +    if (!settings->isFullscreen() && !settings->isPresentationMode()) {
Done in [4bb4d44](https://github.com/xournalpp/xournalpp/pull/5130/commits/4bb4d4466e19e2cbb853fcf8c36fedb478a743a7)
There was also a 4th occurence on line 191

2023-09-13 19:29 UTC, tmoerschell commented
I put the gtk functions into Control::setFullscreen for now. Do you think it would make sense to create an additional function for that in the MainWindow class? If so I'd rather call it MainWindow::setFullscreen(bool enable)

2023-09-16 17:22 UTC, bhennion commented
> I put the gtk functions into Control::setFullscreen for now. Do you think it would make sense to create an additional function for that in the MainWindow class? If so I'd rather call it MainWindow::setFullscreen(bool enable)

Yes I would. The underlying idea is that the MainWindow should be a wrapper around a GtkWindow, and any access to this GtkWindow should go through this wrapper. This is far from being the case right now, but this is some guideline you can keep in mind.

2023-09-16 21:51 UTC, tmoerschell commented
Ok will do, but I'm unsure about the name now: 
`setFullscreen(bool)` looks like a setter for a class member, which isn't the case. 
`goFullscreen(bool)` doesn't sound good for disabling fullscreen. 
`switchFullscreen(bool)` ? Just `fullscreen(bool)` ?
What do you think would fit best?

2023-09-17 12:24 UTC, bhennion commented
> What do you think would fit best?

I guess `setFullscreen(bool)` look like the most natural to me. That's pretty subjective though, so pick the one you prefer.

2023-09-19 13:11 UTC, tmoerschell commented
Ok I found ´toggleFullscreen´ would fit well. Sorry for the delay, everything should be good now

2023-09-22 08:32 UTC, bhennion approved these changes
LGTM! Thanks for the PR!
(Squashing and) Merging in 24 hours unless an objection is raised.

2023-09-23 15:37 UTC, merged