Add marker opacity in select PDF Text options
xournalpp/xournalpp pull request #5139
Opened 2023-09-12 21:35 UTC by jerdoe

This PR adds a menu to specify Marker Opacity for 'Select PDF Text' Tool instead of using the hardcoded value of 60, which could look too faint for some people.

Marker Opacity can be defined using Tools -> Select PDF Text Options -> Marker Opacity.
Fixes #4691

2023-09-14 12:04 UTC, rolandlo requested changes
Thanks for the PR. I like the idea of a customizable opacity for the PDF text selection. However the implementation has some issues and needs to be improved:
- Instead of using the `ToolType` I would suggest to use a new enum `FillType` (with currently 3 values, say `FILL_PEN`, `FILL_HIGHLIGHTER`, `FILL_PDF_TEXT_MARKER`). First of all for most tool types opacity doesn't make sense and secondly the two different pdf text selection modes share the same alpha value.
- In `Control::actionPerformed` you should not pass the active tool, but the enum value that corresponds to the action (e.g. `FILL_PEN` for `ACTION_TOOL_PEN_FILL_OPACITY`)
- The boolean `pen` should be removed from the `FillOpacityDialog` and replaced by the `FillType`
- The callback from `xoj::popup::PopupWindowWrapper<xoj::popup::FillOpacityDialog>` should not use the boolean `pen`, but the `FillType`. The toolHandler should not be used for querying the ToolType or FillType.
- In `xoj::popup::FillOpacityDialog::setPreviewImage` the `pen` property for determining whether to paint an extra rectangle should be replaced by `fillType == FILL_PEN`. The pdf text marker is more like the highlighter than the pen.

2023-09-15 13:47 UTC, jerdoe commented
Thank you very much for having considered my PR and for the very relevant comments.
Feel free to request any other changes or improvements.

2023-09-15 13:50 UTC, jerdoe commented
> Thanks for the PR. I like the idea of a customizable opacity for the PDF text selection. However the implementation has some issues and needs to be improved:
> 
> * Instead of using the `ToolType` I would suggest to use a new enum `FillType` (with currently 3 values, say `FILL_PEN`, `FILL_HIGHLIGHTER`, `FILL_PDF_TEXT_MARKER`). First of all for most tool types opacity doesn't make sense and secondly the two different pdf text selection modes share the same alpha value.
> * In `Control::actionPerformed` you should not pass the active tool, but the enum value that corresponds to the action (e.g. `FILL_PEN` for `ACTION_TOOL_PEN_FILL_OPACITY`)
> * The boolean `pen` should be removed from the `FillOpacityDialog` and replaced by the `FillType`
> * The callback from `xoj::popup::PopupWindowWrapper<xoj::popup::FillOpacityDialog>` should not use the boolean `pen`, but the `FillType`. The toolHandler should not be used for querying the ToolType or FillType.
> * In `xoj::popup::FillOpacityDialog::setPreviewImage` the `pen` property for determining whether to paint an extra rectangle should be replaced by `fillType == FILL_PEN`. The pdf text marker is more like the highlighter than the pen.

Thank you very much for having considered my PR and for the relevant comments.
Feel free to request any other changes or improvements.

2023-09-16 10:58 UTC, rolandlo approved these changes
LGTM! Thanks for cleaning this up so quickly. I have only a very minor nitpick.

2023-09-16 10:58 UTC, rolandlo commented on src/core/gui/PdfFloatingToolbox.cpp
> +    int markerOpacity = pft->theMainWindow->getXournal()->getControl()->getToolHandler()->getSelectPDFTextFill();
A bit more direct:
```suggestion
    int markerOpacity = pft->theMainWindow->getControl()->getToolHandler()->getSelectPDFTextFill();
```

2023-09-16 12:51 UTC, bhennion requested changes
First, thanks for the PR!

I have some concerns about code readability though:

1. This mixes two notions that are very different (at least in the way they are implemented): the alpha value of a stroke (made via the Pdf text highlighter) with the alpha value of a stroke's filling.
2. The enum FillType does not represent various types of filling. I'd call a filling type something like "plain", "stripes" or whatever pattern a stroke could be filled with. Here, FillType really just represents the tool involved in producing the stroke.

2023-09-16 16:12 UTC, jerdoe commented
> First, thanks for the PR!
> 
> I have some concerns about code readability though:
> 
> 1. This mixes two notions that are very different (at least in the way they are implemented): the alpha value of a stroke (made via the Pdf text highlighter) with the alpha value of a stroke's filling.
> 2. The enum FillType does not represent various types of filling. I'd call a filling type something like "plain", "stripes" or whatever pattern a stroke could be filled with. Here, FillType really just represents the tool involved in producing the stroke.

It's all my pleasure!
I feel your concerns. Do you think we should create a specific property in ToolBase to store the pdf text marker opacity or should we extend the approach and consider something like a StrokeAlpha property ?

2023-09-17 12:36 UTC, bhennion commented
I guess using the Color's alpha channel is what'd make the most sense. Right now, this channel is not really used anywhere.

2023-09-19 05:13 UTC, jerdoe commented
> I guess using the Color's alpha channel is what'd make the most sense. Right now, this channel is not really used anywhere.

I've started reworking on it but a question has emerged:
In my new implementation (not yet pushed), pdf marker opacity can be set through the tool settings menu and is stored in the alpha property of Color of the tool 'Select PDF Text...'
Is it planned to add alpha definition through the palette and to store it for each individual color?

When supported, what is the expected behaviour if a user switches color while using pdf text selection. Should it pick up the individual alpha of the selected color or the one defined in the tool settings menu ?

2023-09-19 06:15 UTC, bhennion commented
I think the color chooser dialog and the color buttons should not alter the opacity. Using the already coded opacity slider for that makes more sense I think.

I realized that under the hood, the strokes created by the PdfFloatingToolbox are in fact "filled" strokes, but only as a workaround in order to control the opacity. (see `PdfFloatingToolbox::createStrokes()`). At some point, we should aake the highlighter strokes opacity variable (via the Color::alpha channel) instead of using the fixed StrokeView::HIGHLIGHTER_OPACITY (and remove this workaround).

2023-09-19 06:37 UTC, bhennion commented
Maybe it'd be best to keep this PR somewhat small (maybe just rename the FillType enum or so) and leave a deeper refactor for a future PR.

2023-09-19 20:58 UTC, jerdoe commented on src/core/gui/dialog/SelectOpacityDialog.cpp
> +                        FS(_F("<b>{1} opacity settings</b>\nSelect opacity for {1}") % opacityForLabel).c_str());
Is it designed to be compatible and to support easy translation?

2023-09-19 21:14 UTC, jerdoe commented
Do you have any insights into why it doesn't pass the clang-format test? I've checked it on my local repository by using the following commands:
`git reset --soft HEAD~1
git-clang-format`
and the output states "clang-format did not modify any files."

2023-09-23 14:34 UTC, jerdoe commented
Ready for review. Feel free for any clarifications, changes or improvements.

2023-09-23 15:49 UTC, bhennion reviewed
The code loogs fine to me (besides the following nitpicks).
I'll try to find time to test it soon

2023-09-23 15:49 UTC, bhennion commented on src/core/control/ToolHandler.cpp
> +    void setColor(Color color) {
Could you mark those as `override`?

2023-09-23 15:49 UTC, bhennion commented on src/core/gui/dialog/SelectOpacityDialog.cpp
> +using std::string;
We are trying to avoid `using` statements like those in newly written code
```suggestion
```

2023-09-23 15:49 UTC, bhennion commented on src/core/gui/dialog/SelectOpacityDialog.cpp
> +    string opacityFeatureDesc;
```suggestion
    std::string toolOptionsDesc;
    std::string selectOpacityFor = _("Select opacity for: ");
    std::string opacityFeatureDesc;
```

2023-09-23 19:45 UTC, jerdoe commented
> The code loogs fine to me (besides the following nitpicks). I'll try to find time to test it soon

Thank you for your prompt code review and for highlighting its flaws. Your feedback is greatly appreciated.
No rush at all, take your time to test it whenever you're comfortable.

2023-09-29 16:37 UTC, merged