Fix file open mode in readString
xournalpp/xournalpp pull request #5174
Opened 2023-09-25 03:03 UTC by panpaul

Fix issue with reading files by setting `std::ios::binary` flag when opening file stream. This corrects the file contents being read incorrectly.

For example, in the `LaTeX` preview dialog, `Util::readString` is used to read the generated PDF file. Without setting `std::ios::binary`, the PDF content was loaded incorrectly.

https://github.com/xournalpp/xournalpp/blob/718e57bd9c723723ddf0afdab486201248183125/src/core/control/LatexController.cpp#L318

Should fixes #4740

2023-09-25 04:12 UTC, rolandlo requested changes
Thanks for finding/debugging this issue and providing a PR. 

We use `Util::readString` not only for reading the PDF contents for the LaTeX tool, but also in https://github.com/xournalpp/xournalpp/blob/40fcf731ba30e5890dae358fd0d896bc2ee2254e/src/core/control/Control.cpp#L2108-L2109
and https://github.com/xournalpp/xournalpp/blob/40fcf731ba30e5890dae358fd0d896bc2ee2254e/src/core/gui/dialog/PageTemplateDialog.cpp#L148-L152

to read a page template like this one:

```ini
xoj/template
copyLastPageSize=false
copyLastPageSettings=false
size=595.275591x841.889764
backgroundType=graph
backgroundColor=#ffffffff
```
That is not binary data, so the `std::ios::binary` flag should not be applied in that case.
See https://en.cppreference.com/w/cpp/io/c/FILE#Binary_and_text_modes

So I would suggest to add a parameter `openmode` to `Util::readString` and only pass `std::ios::binary` in the case of the LaTeX PDF contents.

Also please rebase onto `release-1.2`. Your fix should get included in the next minor (bugfix) release and not wait for the next major version.

2023-09-25 05:30 UTC, panpaul commented
Thank you for taking the time to review my changes and provide feedback.

Fixed and rebased onto `release-1.2`

2023-09-25 06:27 UTC, rolandlo commented
/azp run create-installers

2023-09-25 06:46 UTC, LittleHuba commented
The requested installers were generated successfully. The installers are available at:

- [Windows](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjgyODAvYXJ0aWZhY3ROYW1lL3dpbmRvd3M1/content?format=zip)
- [macOS](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjgyODAvYXJ0aWZhY3ROYW1lL21hY09T0/content?format=zip)
- [Debian](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjgyODAvYXJ0aWZhY3ROYW1lL2xpbnV4LWRlYmlhbi1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 20.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjgyODAvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMC4wNC1wYWNrYWdlcw2/content?format=zip)
- [Ubuntu 22.04](https://artprodsu6weu.artifacts.visualstudio.com/A4bb312fe-95d7-456e-96fb-7669bb27c94b/ce85de88-4b71-44a0-8a57-2707c0b9a6e7/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3hvdXJuYWxwcC9wcm9qZWN0SWQvY2U4NWRlODgtNGI3MS00NGEwLThhNTctMjcwN2MwYjlhNmU3L2J1aWxkSWQvMjgyODAvYXJ0aWZhY3ROYW1lL2xpbnV4LXVidW50dS0yMi4wNC1wYWNrYWdlcw2/content?format=zip)

Please be aware that these links are only valid for a limited time (~30 days).

2023-09-25 07:40 UTC, rolandlo commented
@Marijkevandesteene can you please use the installer from https://github.com/xournalpp/xournalpp/pull/5174#issuecomment-1733019255 to check if #4740 is solved with this PR.

2023-09-25 15:39 UTC, Marijkevandesteene commented
Can you please use the installer from [#5174 (comment)](https://github.com/xournalpp/xournalpp/pull/5174#issuecomment-1733019255) to check if #4740 is solved with this PR.

Hi @rolandlo, @panpaul  I have installed the windows version and the problem appears to be solved with this PR. I will close the issue and thanks a lot for resolving this issue. 

Thanks a lot for resolving the issue. 

One small question. This resolution is also available in the following versions of Xournalpp?

2023-09-25 15:59 UTC, rolandlo approved these changes
Merging in 24 hours if no objections are raised.

2023-09-25 16:54 UTC, rolandlo commented
> 
> One small question. This resolution is also available in the following versions of Xournalpp?

This resolution will be available in version 1.2.2 and all future versions of Xournal++ (1.2.3, 1.3.0 etc.). It will not arrive in the nightly builds right away though. We first have to merge back the release-1.2 branch back into master.

2023-09-25 17:41 UTC, rolandlo commented
Fixes #4740. Fixes  #4335. Fixes #4933.

2023-09-26 05:50 UTC, Marijkevandesteene commented
Thank you for the reply.
I will work on the available version.
I believe I will be able to follow the status / merge back to the master on the ticket in github.

Thanks, with kind regards,
Marijke
________________________________
Van: Roland Lötscher ***@***.***>
Verzonden: maandag 25 september 2023 18:54
Aan: xournalpp/xournalpp ***@***.***>
CC: Marijkevandesteene ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [xournalpp/xournalpp] Fix file open mode in readString (PR #5174)


One small question. This resolution is also available in the following versions of Xournalpp?

This resolution will be available in version 1.2.2 and all future versions of Xournal++ (1.2.3, 1.3.0 etc.). It will not arrive in the nightly builds right away though. We first have to merge back the release-1.2 branch back into master.

—
Reply to this email directly, view it on GitHub<https://github.com/xournalpp/xournalpp/pull/5174#issuecomment-1734130204>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AETXMFPRFHJA72YDJLTSPG3X4GZL7ANCNFSM6AAAAAA5FM75XA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-09-26 15:46 UTC, merged

2023-09-26 15:47 UTC, rolandlo commented
Thanks again @panpaul for the fix of this hidden bug! I just merged it.