Add feature to remove individual recent documuents
xournalpp/xournalpp pull request #5789
Opened 2024-08-06 23:02 UTC by JayC180

Added submenu "Remove Recent Documents" under menu file -> recent documents. Clicking on files in this submenu remove individual recent files without the need of clearing the whole list.

2024-08-26 03:21 UTC, rolandlo requested changes
Thanks a lot for your contribution. I have missed that feature as well.

Purely UX-wise (especially when removing multiple recent documents) the Gnome-text-editor way of combining the recent document with a remove icon in a list view would look preferable.
![grafik](https://github.com/user-attachments/assets/f4402f04-428d-465a-90d4-89af5d1ce7d9)
It would be harder to implement though and reduce consistency among menus.

So I'm fine with the approach you took.

The feature appears to work fine. I have some comments (see in code).
Please also revert the changes to RecentManager.cpp, as they are pure formatting changes unrelated to this PR.

2024-08-26 03:21 UTC, rolandlo commented on src/core/gui/menus/menubar/RecentDocumentsSubmenu.cpp
> +}
missing newline

2024-08-26 03:21 UTC, rolandlo commented on src/core/gui/menus/menubar/RecentDocumentsSubmenu.cpp
> +        GMenu* removeSubmenu = g_menu_new();
Is that data every freed? It doesn't look like it.

2024-08-26 03:21 UTC, rolandlo commented on src/core/gui/menus/menubar/RecentDocumentsSubmenu.cpp
> +        start_index++;
Please keep it consistent with the corresponding line(s) in `createRecentMenu`.

2024-08-26 05:25 UTC, JayC180 commented
Thank you very much for the review! I have updated the code accordingly.
Regarding the UI suggestion, I also think adding a remove icon would be nice, as that was what I attempted at first. Unfortunately, I am unfamiliar with GTK and not skilled enough to implement that. I recommend creating another issue as enhancement for ui, so it could be picked up by someone with more expertise, and I might attempt that again in the future. Thanks!

2024-08-26 05:59 UTC, rolandlo approved these changes
LGTM. Can you please squash your commits into one?

2024-08-26 06:20 UTC, JayC180 commented
Done!

2024-08-26 06:21 UTC, rolandlo approved these changes
Thanks for quickly addressing the review.
Merging in 48 hours if no objections are raised.

2024-08-26 07:47 UTC, rolandlo commented
It removes individual entries from the list of recent documents. The documents themselves are not removed.

2024-08-26 15:56 UTC, JayC180 commented
Thanks for the feedbacck! I have added some C_ in RecentDocumentsSubmenu.cpp, hope I did that correctly.

2024-08-27 14:19 UTC, JayC180 commented on src/core/gui/menus/menubar/RecentDocumentsSubmenu.cpp
> +                C_("RemoveInRecentDocumentsSubmenu", "Remove Recent Documents"), G_MENU_MODEL(removeSubmenu));
Thank you for the explaination! I have updated the file with a more thorough context.

2024-08-30 09:48 UTC, merged